import urllib

import json

LICENSE_FULLTEXT_DOWNLOAD_TEMPLATE = "https://raw.githubusercontent.com/spdx/license-list-data/refs/heads/main/text/{}.txt"

def generate_license_fulltext_download_script(license_ids, script_filename="spdx/download_fulltext.sh"):
    """
    Generates the full text download bash script for a given license IDs, and saves it to a file.
    :param license_ids: The license IDs to generate the script for.
    :param script_filename: The filename to save the script to.
    """
    with open(script_filename, 'w', encoding='utf-8') as script_file:
        script_file.write("#!/bin/bash\n# AUTOGENERATED FILE BY spdx_download.py\n\n")
        for license_id in license_ids:
            # URL-encode the license ID to handle special characters
            license_id = urllib.parse.quote(license_id)
            download_url = LICENSE_FULLTEXT_DOWNLOAD_TEMPLATE.format(license_id)
            script_file.write(f"curl -o spdx/{license_id}.txt {download_url}\n")
    print(f"Generated download script: {script_filename}")

def download_osadl_matrix_licenses_fulltext(matrix_filename="osadl/matrixseqexpl.json"):
    """
    Downloads the full text of all licenses in the OSADL matrix.
    :param matrix_filename: The filename of the OSADL matrix JSON file.
    """
    license_ids = []
    try:
        with open(matrix_filename, 'r', encoding='utf-8') as file:
            matrix = json.load(file)

        for entry in matrix["licenses"]:
            license_id = entry.get("name")
            if license_id:
                license_ids.append(license_id)
    except FileNotFoundError:
        print(f"Matrix file {matrix_filename} not found.")
    except json.JSONDecodeError:
        print(f"Error decoding JSON from {matrix_filename}.")

    if len(license_ids) > 0:
        print(f"Found {len(license_ids)} licenses in the OSADL matrix. Generating download script...")
        generate_license_fulltext_download_script(license_ids)
    else:
        print("No licenses found in the OSADL matrix.")

if __name__ == "__main__":
    download_osadl_matrix_licenses_fulltext()