#! /bin/bash

rm *.txt

wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/0BSD.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/AFL-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/AFL-2.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/AFL-3.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/AGPL-3.0-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/AGPL-3.0-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Apache-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Apache-1.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Apache-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Artistic-1.0-Perl.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Artistic-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Artistic-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-1-Clause.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-2-Clause-Patent.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-2-Clause.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-3-Clause-Open-MPI.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-3-Clause.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-4-Clause-UC.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-4-Clause.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-4.3TAHOE.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSD-Source-Code.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BSL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Bitstream-Vera.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/BlueOak-1.0.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/CC-BY-2.5.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/CC-BY-3.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/CDDL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/CDDL-1.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/CPL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/ECL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/ECL-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/EFL-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/EPL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/EPL-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/EUPL-1.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/EUPL-1.2.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/FSFAP.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/FSFUL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/FSFULLR.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/FSFULLRWD.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/FTL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-1.0-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-1.0-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-2.0-only%20WITH%20Classpath-exception-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-2.0-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-2.0-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-3.0-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/GPL-3.0-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/HPND.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/IBM-pibs.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/ICU.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/IJG.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/IPL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/ISC.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/ImageMagick.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Info-ZIP.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/JasPer-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LGPL-2.0-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LGPL-2.0-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LGPL-2.1-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LGPL-2.1-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LGPL-3.0-only.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LGPL-3.0-or-later.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Libpng.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LicenseRef-scancode-bsla-no-advert.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LicenseRef-scancode-info-zip-2003-05.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/LicenseRef-scancode-ppp.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MIT-CMU.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MIT.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MPL-1.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MPL-2.0-no-copyleft-exception.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MPL-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MS-PL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MS-RL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Minpack.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/MirOS.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/NBPL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/NCSA.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/NTP.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/OFL-1.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/OGC-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/OLDAP-2.8.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/OSL-3.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/OpenSSL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/PHP-3.01.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/PostgreSQL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Python-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Qhull.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/RSA-MD.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/SGI-B-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/SMLNJ.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/SSH-OpenSSH.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/SSH-short.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Saxpath.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Sleepycat.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Spencer-86.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/SunPro.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/UPL-1.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Unicode-DFS-2015.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Unicode-DFS-2016.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Unlicense.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/W3C-19980720.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/W3C-20150513.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/W3C.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/WTFPL.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/X11.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/XFree86-1.1.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/ZPL-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/Zlib.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/blessing.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/bzip2-1.0.5.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/bzip2-1.0.6.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/curl.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/libpng-2.0.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/libtiff.txt
wget -4 https://www.osadl.org/fileadmin/checklists/unreflicenses/zlib-acknowledgement.txt