#! /bin/bash

rm *.txt

wget -4 https://www.osadl.org/fileadmin/checklists/terms/Advertisement.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Any%20third%20party.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Appropriate%20legal%20notices.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Appropriately.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Attribution%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Authorship.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Beginning.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Binary%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Binary-only%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Change%20date.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Circumstances.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Circumvention.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Combined%20library.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Combined%20work%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Combined%20work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Commercial%20distribution.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Compatible%20license.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Contributors.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Copy.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Copyright%20holder.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Copyright%20license.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Copyright%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Customary%20medium.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Customary%20method.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Database%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Debugging.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Delayed%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Delayed%20source%20code%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Distribution%20material.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Documentation.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Documented%20format.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Duration.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Dynamic.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Easily.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Effective.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Equivalent.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Feasible.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/File.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Font%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Font.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/For%20own%20use.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Functionality.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Granted%20rights.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Header%20file.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Human-readable.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Identical.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Image%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Including.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Installation%20information.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Installation%20scripts.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Installation.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Installed.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Interactive.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Interface.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Interoperable.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Irrelevant%20parts.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Legal%20notices.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Liability%20disclaimer.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Library.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20acceptance.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20announcement.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20change.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20exception.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20fee.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20obligation.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License%20text.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/License.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Linkable%20work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Linked%20work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Machine-readable.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modification%20author.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modification%20date.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modification%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modification%20reason.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modification%20report.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modification.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modified%20library.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Modified%20work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Name.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Network%20service.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/No%20charge.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/No%20profit.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Non-FOSS%20restrictions.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Non-permissive%20additional%20terms.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/On%20behalf%20of.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/On%20other%20server.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/On%20same%20server.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Original%20author.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Original%20license.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Original%20name.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Original%20source%20code.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Original%20work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Other%20contributors.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Other%20works.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Patent%20holder.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Patent%20license.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Patent%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Pointer.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Preexisting.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Prejudicial.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Product%20name.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Product.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Protocol%20incompatible.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Public%20domain.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Reasonable.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Recipient.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Relinking.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Request.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Retrieval%20information.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Reverse%20engineering.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Running.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Same%20medium.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Separate.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Service%20offerings.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Shared%20library.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Software%20modification.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Source%20code%20delivery.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Source%20code%20modification.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Source%20code.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Stand-alone.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Standard%20license%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Strong%20copyleft%20license.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Substantial%20font%20modification.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Substantial%20source%20code%20modification.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Substantial%20work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Target%20binary.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Technological%20measures.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Third-party%20attribution%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Third-party%20patents.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Third-party%20trademarks.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Timely.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Title.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Tool%20chain%20information.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Trademark%20holder.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Trademark%20notice.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Transferable.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Uncombined.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Usage.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/User%20product.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Verbatim.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Via%20Internet.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Via%20peer-to-peer%20transmission.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Viewable.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Warranty%20disclaimer.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Windows%20code.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Work.txt
wget -4 https://www.osadl.org/fileadmin/checklists/terms/Written%20offer.txt